config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :articles do
    resources :comments
  end
  root 'home#index'
  get 'home/index'
  get 'contacts/index'
  post '/contacts', to: 'contacts#create', as: :contacts
  

  #get "articles", to:"articles#index", as: :articles
  
  #get 'articles/new'
  #get 'articles/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/add_column_to_contact.rb
class AddColumnToContact < ApplicationRecord
end

app/models/add_status_to_article.rb
class AddStatusToArticle < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence:true, length:{minimum:5}
    validates :content, presence:true, length:{minimum:10}
    validates :status, presence:true
    scope :status_active, ->{where(status:'active')}
    has_many :comments, dependent: :destroy
end

app/models/change_status_from_contact.rb
class ChangeStatusFromContact < ApplicationRecord
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    before_create :default_status
    validates :username, presence:true, length:{minimum:5}
    validates :content, presence:true, length:{minimum:10}
    scope :status_active, ->{where(status:'Dirilis')}
    belongs_to :article

    def default_status
        self.status = 'Active'
    end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence:true, length:{minimum:5}
    validates :message, presence:true, length:{minimum:10}
end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :password
    before_save :add_salt_and_hash
    before_create :add_activation_token
    def add_activation_token
        self.activation_token = SecureRandom.urlsafe_base64
        self.activation_status = "not activated"
    end

    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, on: :create,
    length: { minimum: 5 },
    confirmation: true

    def add_salt_and_hash
        unless password.blank?
            self.password_salt = BCrypt::Engine.generate_salt
            self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user, :check_current_user

    def current_user
        current_user ||= User.where("id = ?", session[:user]).first
    end

    def check_current_user
        if current_user.blank?
            flash[:error] = "please login first before run the action"
            redirect_to new_session_url
        else
            current_user
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_current_user, only: [:index, :new, :create, :edit, :update, :destroy]
  def index
    #@articles = Article.all.order("created_at DESC")
    @articles = Article.page(params[:page]).per(3)
    #@article = Article.new
    respond_to do |format|
      if params[:search].present?
        format.js{
          @articles = Article.where("title like ? or content like ?", "%#{params[:search]}%","%#{params[:search]}%").page(params[:page]).per(2)
        }
        format.html
      else
        format.html
      end
    end
  end

  def new
    @article = Article.new
  end
  
  def show
    @article = Article.find_by_id(params[:id])
    @comments = @article.comments.order("id desc")
    @comment = Comment.new
    # @comment = Comment.all
  end

  def edit
    @article = Article.find_by_id(params[:id])
  end

  def update
    @article = Article.find_by_id(params[:id])
    if @article.update(params_article)
      flash[:success] = "Success Update Records"
      redirect_to action:'index'
    else 
      flash[:error] = "data not valid"
      render'edit'
    end
  end

  def destroy
    @article = Article.find_by_id(params[:id])
    if @article.destroy
      flash[:success] = "Success Delete Records"
      redirect_to action: "index"
    else
      flash[:error] ="Failed Delete"
      redirect_to action: "index"
    end
  end

  def create
    @article = Article.new(params_article)
    if @article.save
      flash[:success] = "Success Add Records"
      redirect_to action: 'index'
    else
      flash[:error] = "Data not valid"
      render 'new'
    end
  end

  private
  def params_article
    params.require(:article).permit(:title, :content, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_current_user, only:[:new, :create, :edit, :update, :destroy]
  def show
    @comment = Comment.find_by_id(params[:id])
  end


  def create
    respond_to do |format|
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(params_comments)

      if @comment.save
        #format.js { @article }
        format.js{article=Article.find(params[:article_id])}
        redirect_to article_path(@article.id)
      else
        format.js{article=Article.find(params[:article_id])}
        render article_path(@article)
      end
    end
  end
  
  # def create
  #   @comment = Comment.new(params_comment)
  #   if @comment.save
  #     flash[:success] = "Success Add Records"
  #     redirect_to action: 'index'
  #   else
  #     flash[:error] = "Data not valid"
  #     render 'new'
  #   end
  # end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def params_comments
    params.require(:comment).permit(:article_id, :username, :content, :status)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params_contact)
    if @contact.save
      flash[:success] = "Success Add Records"
      redirect_to action: 'index'
    else
      flash[:error] = "Data not valid"
      render 'index'
    end
  end

  private
  def params_contact
    params.require(:contact).permit(:name, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_current_user, only: [:index]
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    username = params[:username]
    password = params[:password]
    user = User.where("username =?", username).first
    user_password = BCrypt::Engine.hash_secret(password, user.password_salt) unless user.blank?
    if !user_password.blank? and user.password_hash.eql? user_password
      session[:user] = user.id
      flash[:notice] = "Welcome #{user.username}"
      redirect_to root_url
    else
      params[:username]
      flash[:error] = "Your data not valid"
      render "new"
    end
  end
  def destroy
    session[:user] = nil
    flash[:notice] = "logout session success"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(params_user)
    if @user.save
        flash[:notice] = "Success Add Records"
        redirect_to root_url
    else
        flash[:error] = "data not valid"
        render "new"
    end
  end

  private
  def params_user
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/_article.html.erb
<h4><%=article.title %></h4>
<h5 style ="margin-left: 15px"><%= article.content.truncate(30) %></h5>
<h6 style ="margin-left: 15px">status : <%= article.status %></h6>
<span style ="margin-left: 15px"><%= link_to 'read more',  article_path(article.id) %></span>
<span> | </span>
<span><%= link_to 'edit', edit_article_path(article.id)%></span>
<span> | </span>
<span> <%= link_to 'delete', article_path(article.id), method:"DELETE", data:{confirm:'Delete this data?'} %> </span>
<p>____________________________________</p>

app/views/articles/edit.html.erb
<div class="jumbotron text-center">
    <h2>Edit Article</h2>
</div>

<div class="container" style="margin-top:30px">
<h3>Edit article:</h4>
  <div class="row">
    <div class="col-sm-4">

        <%= form_for @article do |f| %>
            <%= f.label:title %>
            <br/>
            <%= f.text_field :title %>
            <br/>
            <%= f.label :content %>
            <br/>
            <%= f.text_area :content, cols:20, rows:10 %>
            <br/>
            <%= f.label :status %>
            <br/>
            <%= f.radio_button :status, 'active' %>
            <%= label :article_status, 'active' %>
            <%= f.radio_button :status, 'off' %>
            <%= label :article_status, 'off' %>
            <br/>
            <%= f.submit :submit %>
        <% end %>

        <div>
            <%=link_to "Back to article", article_path %>
        </div>

      </div>
  </div>
</div>

app/views/articles/index.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<div class="jumbotron text-center">
    <h2>Articles</h2>
</div>

<header class="masthead" style="background-image: url('img/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Articles</h1>
          <span class="subheading">A Blog Theme by Start Bootstrap</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!--
<div id="myCarousel" class="carousel slide">

  <!-- Indicators ->
  <ul class="carousel-indicators">
    <li class="item1 active"></li>
    <li class="item2"></li>
    <li class="item3"></li>
  </ul>
  
  <!-- The slideshow ->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="" alt="Los Angeles" width="1100" height="500">
    </div>
    <div class="carousel-item">
      <img src="" alt="Chicago" width="1100" height="500">
    </div>
    <div class="carousel-item">
      <img src="">
    </div>
  </div>
  
  <!-- Left and right controls ->
  <a class="carousel-control-prev" href="#myCarousel">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#myCarousel">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>
-->



<div class="container" style="margin-top:30px">
<h3>Article posted:</h4>
  <div class="row">
    <div class="col-sm-4" id="article_list">
      <%= render @articles %>
      <%= paginate @articles %>
    </div>
    <div class="col-sm-4">
    </div>
    <div class="col-sm-4">
        <h5>
        <% if !current_user %>
        <%= link_to 'Log-in', new_session_path %>
        <% else %>
        Hello <%= current_user.username %>
        <%= link_to 'Log-Out', session_path(current_user.id), method: "DELETE" %>
        <% end %>
        </h5>
        <form id="get_search">
          <input class="form-control-sm" type="search" placeholder="Type here to search" aria-label="Search" id="search" name="search">
          <input class="btn btn-sm btn-outline-info" type="button" onclick="submitFrmAjax();" value="Search">
        </form>
      </div>
  </div>
  
  <%= link_to 'Create a new article', new_article_path%>
</div>
</div>

app/views/articles/index.js.erb
$('#article_list').html("<%= j(render @articles)%>");

app/views/articles/new.html.erb
<div class="jumbotron text-center">
    <h2>Create New Articles</h2>
</div>

<div class="container" style="margin-top:30px">
<h3>Create new article:</h4>
  <div class="row">
    <div class="col-sm-4">
        <%=form_for @article do |f| %>
            <%= f.label :title  %>
            <br/>
            <%= f.text_field :title %>
            <%= @article.errors[:title].first unless @article.errors[:title].blank?  %>
            <br/>
            <%= f.label :content %>
            <br/>
            <%= f.text_area :content, cols:20, rows:10 %>
            
            <br/>
            <% f.label :status %>
            <%= f.radio_button :status, "active" %>
            <%= label :article_status, "active" %>
            <%= f.radio_button :status, "off", :checked => true %>
            <%= label :article_status, "off" %>
            <br/>
            <%= f.submit :submit %>
        <% end %>
      </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container" style="margin-top:30px">
  <div class="row">
    <div class="col-sm-4">
        <h2>Show Articles</h2>

        <h3><%= @article.title %></h3>
        <p><%= @article.content %></p>
        <span>status: <%= @article.status %></span>
        <p>
            <%= link_to 'index', articles_path %>
        </p>
         
         <% @article.comments.each do |c| %>
              <strong><%= c.username %>:</strong>
              <br/>
              <%= c.content %>
              <br/>
              <br/>
          <% end %>
    </div>
    <div class="col-sm-4">
    </div>
    <div class="col-sm-4">
      <h5>Submit your reply:</h5>
      <%= render 'comments/form' %>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<br/><br/>
<h3>Comments:</h3>
<% @article.comments.each do |c| %>
    <strong><%= c.username %>:</strong>
    <br/>
    <%= c.content %>
    <br/>
    <br/>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build], remote:true, html: {id: :form_id}) do |f| %>
    <%= f.hidden_field :article_id, value: @article.id %>
    <%= f.label :username  %>
    <br/>
    <%= f.text_field :username %>
    <%= @comment.errors[:username].first unless @comment.errors[:username].blank?  %>
    <br/>
    <%= f.label :content %>
    <br/>
    <%= f.text_area :content, cols:20, rows:10 %>
    
    <br/>
    <%= f.submit :submit %>
<% end %>

app/views/comments/create.js.erb
<% if @comment.errors.present? %>
    $('#form-comment).html("<%= j(render 'comments/form' %>")
    $($(".field_with_errors")[0]).append("<p class='message'><%= escape+javascript(@comment.errors[:content].first) %>)</p>
<% else %>
    $("#list-comments").html(" <%= j( render @article.comments.order("id desc") ) %>");
    $("#text_username").val('');
    $("#text_content").val('');
    $("div.field_with_errors p.message").remove();
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/contacts/index.html.erb
<div class="jumbotron text-center">
    <h2>Contact us</h2>
</div>

<div class="container" style="margin-top:30px">
<h3>Contact us by filling this form</h3 >
  <div class="row">
    <div class="col-sm-4">
      <%=form_for @contact do |f| %>
          <%= f.label :name  %>
          <br/>
          <%= f.text_field :name %>
          <br/>
          <%= f.label :message %>
          <br/>
          <%= f.text_area :message, cols:20, rows:10 %>
          <br/>
          <%= f.submit :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

<div class="jumbotron text-center">
  <h1>My First Bootstrap Page</h1>
  <p>Resize this responsive page to see the effect!</p> 
</div>
  
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>Column 1</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
    <div class="col-sm-4">
      <h3>Column 2</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
    <div class="col-sm-4">
      <h3>Column 3</h3>        
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/Article.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mudahmudahanbisa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mudahmudahanbisa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav" style="margin-bottom:500">
        <li class="nav-item">
            <a class="nav-link"><%= link_to 'Home', root_path, :class=>"nav-link" %></a>
        </li>
        <li class="nav-item">
            <a class="nav-link"><%= link_to 'Articles',  articles_path, :class=>"nav-link" %></a>
        </li>
        <li class="nav-item">
            <a class="nav-link"><%= link_to 'New Article',  new_article_path, :class=>"nav-link" %></a>
        </li>
        <li class="nav-item">
            <a class="nav-link"><%= link_to 'Contact Us', contacts_index_path, :class=>"nav-link"%></a>
        </li>    
        </ul>
    </div>  
    </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mudahmudahanbisa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<%= f.label :username %>
<br/>
<%= f.text_field :username %>
<%= @user.errors[:username].first unless @user.errors[:username].blank? %>
<br/>
<%= f.label :email %>
<br/>
<%= f.text_field :email %>
<%= @user.errors[:email].first unless @user.errors[:email].blank? %>
<br/>
<%= f.label :password %>
<br/>
<%= f.password_field :password %>
<%= @user.errors[:password].first unless @user.errors[:password].blank? %>
<br/>
<%= f.label :password_confirmation %>
<br/>
<%= f.password_field :password_confirmation %>
<%= @user.errors[:password_confirmation].first unless @user.errors[:password_confirmation].blank? %>
<br/>
<%= f.submit %>
<% end %>